-- NON-LOSSLESS ROLLBACK placeholder
ALTER TABLE orders DROP CONSTRAINT IF EXISTS fk_orders_user;
DROP INDEX CONCURRENTLY IF EXISTS idx_orders_status;
ALTER TABLE orders ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN amount DROP DEFAULT;
ALTER TABLE orders RENAME COLUMN amount TO total_price;


