name: schema-agent

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  plan-migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install schema-pilot
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/tarunms7/schema-pilot.git
      - name: Capture head/base
        run: |
          echo "HEAD_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          mkdir -p $RUNNER_TEMP/base
          git --work-tree=$RUNNER_TEMP/base checkout ${{ github.event.pull_request.base.sha }} -- .
          echo "BASE_PATH=$RUNNER_TEMP/base" >> $GITHUB_ENV
      - name: Run schema-agent
        run: |
          mkdir -p artifacts
          python -m schema_agent.cli \
            --base-dir "$BASE_PATH" --base-module app.db.base \
            --head-dir "$HEAD_PATH" --head-module app.db.base \
            --dialect postgresql \
            --out-dir artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: schema-agent-sql
          path: |
            artifacts/forward.sql
            artifacts/rollback.sql
      - name: Comment SQL summary to PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            function readFileSafe(path) {
              try { return fs.readFileSync(path, 'utf8'); } catch (e) { return ''; }
            }
            const max = 60000; // GH comment body limit ~65k
            const fsql = readFileSafe('artifacts/forward.sql');
            const rsql = readFileSafe('artifacts/rollback.sql');
            const fshow = fsql ? fsql.slice(0, max) + (fsql.length > max ? '\n-- [truncated]' : '') : '-- forward.sql not found';
            const rshow = rsql ? rsql.slice(0, max) + (rsql.length > max ? '\n-- [truncated]' : '') : '-- rollback.sql not found';
            const body = `Schema Agent generated SQL.\n\nForward SQL:\n\n\`\`\`sql\n${fshow}\n\`\`\`\n\nRollback SQL:\n\n\`\`\`sql\n${rshow}\n\`\`\``;
            const { owner, repo } = context.repo;
            await github.rest.issues.createComment({ owner, repo, issue_number: context.issue.number, body });
